### ISSUE TITLE
MIDI program changes not being sent to NESizer

### ISSUE THREAD

**Issue by jeff464** [Jaffe-/NESizer2#32]
If I send a program change from my sequencer to the NESizer, nothing happens. Might it be possible to add this?

**Comment by beau-seidon** [comment]
It actually looks pretty easy to implement this without breaking anything else. I'll give it a whack this evening. 

There looks to be functionality for handling patch changes via SysEx already, but I think program change would definitely be more user friendly. 
My MPK Mini Plus has pads that can be configured to send PC messages, and that's how I change sequences in my MidiGAL. 
I don't have anything that's not a computer or DIY that can send custom SysEx messages for controlling synths.

**Comment by beau-seidon** [comment]
done!  you can get it it right now from my [midi-patch-change](https://github.com/beau-seidon/NESizer2/tree/midi-patch-change) branch

sorry I said I would work on it sooner, but I couldn't get around to it til tonight. 
been busy with work, and coding another doodad i built.

I promised a build guide over a year ago lol. it's still only 3/4 finished. :|
